#!/bin/bash
# Start/stop Graylog service
#
. /lib/svc/share/smf_include.sh

NAME=graylog
VERSION=2.4.6

GRAYLOG_HOME=/usr/${NAME}/${VERSION}
GRAYLOG_USER=root
GRAYLOG_GROUP=sys

# The following variables can be overwritten in $DEFAULT

# Java home directory
#JAVA_HOME=

# Additional Java OPTS
#JAVA_OPTS=

# log directory
LOG_DIR=/var/log/${NAME}

# configuration file
GRAYLOG_CONF=/etc/${NAME}/${VERSION}/graylog.conf

# PID file
PID_DIR=/var/run/${NAME}

# End of variables that can be overwritten in $DEFAULT

GRAYLOG_ENV=${GRAYLOG_HOME}/bin/env
APPPATH=${GRAYLOG_HOME}/bin/elasticsearch

[ -f ${GRAYLOG_ENV} ] && . ${GRAYLOG_ENV}

# Define other required variables
LOG_FILE=${LOG_DIR}/${NAME}.log
GRAYLOG_PID="${PID_DIR}/${NAME}.pid"
DAEMON=${GRAYLOG_HOME}/bin/graylogctl

export JAVA_HOME
export JAVA_OPTS
export LOG_FILE
export GRAYLOG_CONF
export GRAYLOG_PID

# Check DAEMON exists
test -x ${DAEMON} || exit ${SMF_EXIT_ERR_FATAL}

checkJava() {
  if [ -x "${JAVA_HOME}/bin/java" ]; then
    JAVA="${JAVA_HOME}/bin/java"
  else
    JAVA=`which java`
  fi

  if [ ! -x "${JAVA}" ]; then
    echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
    exit ${SMF_EXIT_ERR_FATAL}
  fi
}

case "$1" in
  'start')
    checkJava
    [ -f ${GRAYLOG_PID} ] && stop
    mkdir -p ${LOG_DIR}
    chown ${GRAYLOG_USER}:${GRAYLOG_GROUP} ${LOG_DIR}
    mkdir -p ${PID_DIR}
    chown ${GRAYLOG_USER}:${GRAYLOG_GROUP} ${PID_DIR}
    if [ "${GRAYLOG_USER}" == "root" ]; then
       ${DAEMON} start &
    else
       su - ${GRAYLOG_USER} -c "[ -f ${GRAYLOG_ENV} ] && . ${GRAYLOG_ENV}; ${DAEMON} start" &
    fi
   ;;
'restart')
  stop
  start
  ;;
'stop')
  ${DAEMON} stop
  ;;
*)
  echo "Usage: $0 { start | stop | restart}"
  exit ${SMF_EXIT_ERR_FATAL}
  ;;
esac

exit ${SMF_EXIT_OK}

