--- a/Makefile	2016-10-26 08:21:49.083432826 +0200
+++ b/Makefile	2016-10-26 11:03:18.406923181 +0200
@@ -1,5 +1,5 @@
 # Compatibility with GNU/Linux [i.e. Debian] based distros
-UNAME_OS_GNU := $(shell if uname -o | grep -q "GNU/Linux" ; then echo true; else echo false; fi)
+UNAME_OS_GNU := $(shell if uname | grep -q "GNU/Linux" ; then echo true; else echo false; fi)
 DISTRO_DEBIAN := $(shell if [ -e /etc/debian_version ] ; then echo true; else echo false; fi)
 IS_DEBIAN=false
 DISTRO_DEBIAN_VER_8=false
@@ -81,12 +81,12 @@
 	BASH_COMPLETION_DIR=${DESTDIR}/etc/bash_completion.d
 endif
 
-install:
+install: install_pcsd
 	$(PYTHON) setup.py install --root=$(or ${DESTDIR}, /) ${EXTRA_SETUP_OPTS}
 	mkdir -p ${DESTDIR}${PREFIX}/sbin/
 	mv ${DESTDIR}${PREFIX}/bin/pcs ${DESTDIR}${PREFIX}/sbin/pcs
 	install -D -m644 pcs/bash_completion.sh ${BASH_COMPLETION_DIR}/pcs
-	install -m644 -D pcs/pcs.8 ${DESTDIR}/${MANDIR}/man8/pcs.8
+	install -m644 -D pcs/pcs.8 ${DESTDIR}${MANDIR}/man8/pcs.8
 ifeq ($(IS_DEBIAN),true)
   ifeq ($(install_settings),true)
 	rm -f  ${DESTDIR}${PYTHON_SITELIB}/pcs/settings.py
@@ -100,7 +100,7 @@
 
 install_pcsd:
 ifeq ($(BUILD_GEMS),true)
-	make -C pcsd build_gems
+	DESTDIR= make -C pcsd build_gems
 endif
 	mkdir -p ${DESTDIR}/var/log/pcsd
 ifeq ($(IS_DEBIAN),true)
@@ -117,25 +117,25 @@
 	        rm -f $$tmp_settings_pcsd
   endif
   ifeq ($(IS_SYSTEMCTL),true)
-	install -d ${DESTDIR}/${systemddir}/system/
-	install -m 644 pcsd/pcsd.service.debian ${DESTDIR}/${systemddir}/system/pcsd.service
+	install -d ${DESTDIR}${systemddir}/system/
+	install -m 644 pcsd/pcsd.service.debian ${DESTDIR}${systemddir}/system/pcsd.service
   else
-	install -m 755 -D pcsd/pcsd.debian ${DESTDIR}/${initdir}/pcsd
+	install -m 755 -D pcsd/pcsd.debian ${DESTDIR}${initdir}/pcsd
   endif
 else
 	mkdir -p ${DESTDIR}${PREFIX}/lib/
-	cp -r pcsd ${DESTDIR}${PREFIX}/lib/
+	cp -L -r pcsd ${DESTDIR}${PREFIX}/lib/
 	install -m 644 -D pcsd/pcsd.conf ${DESTDIR}/etc/sysconfig/pcsd
 	install -d ${DESTDIR}/etc/pam.d
 	install  pcsd/pcsd.pam ${DESTDIR}/etc/pam.d/pcsd
   ifeq ($(IS_SYSTEMCTL),true)
-	install -d ${DESTDIR}/${systemddir}/system/
-	install -m 644 pcsd/pcsd.service ${DESTDIR}/${systemddir}/system/
+	install -d ${DESTDIR}${systemddir}/system/
+	install -m 644 pcsd/pcsd.service ${DESTDIR}${systemddir}/system/
 # ${DESTDIR}${PREFIX}/lib/pcsd/pcsd holds the selinux context
 	install -m 755 pcsd/pcsd.service-runner ${DESTDIR}${PREFIX}/lib/pcsd/pcsd
 	rm ${DESTDIR}${PREFIX}/lib/pcsd/pcsd.service-runner
   else
-	install -m 755 -D pcsd/pcsd ${DESTDIR}/${initdir}/pcsd
+	install -m 755 -D pcsd/pcsd ${DESTDIR}${initdir}/pcsd
   endif
 endif
 	install -m 700 -d ${DESTDIR}/var/lib/pcsd
