diff -Nura a/Makefile b/Makefile
--- a/Makefile	2016-10-28 17:52:57.014552276 +0200
+++ b/Makefile	2016-10-28 19:03:50.299333591 +0200
@@ -78,14 +78,15 @@
 
 
 ifndef BASH_COMPLETION_DIR
-	BASH_COMPLETION_DIR=${DESTDIR}/etc/bash_completion.d
+	BASH_COMPLETION_DIR=/etc/bash_completion.d
 endif
 
-install:
-	$(PYTHON) setup.py install --root=$(or ${DESTDIR}, /) ${EXTRA_SETUP_OPTS}
+install: install_pcsd
+	$(PYTHON) setup.py install --root=$(or ${DESTDIR}, /) ${EXTRA_SETUP_OPTS} \
+		--install-lib=$(PYTHON_SITELIB)
 	mkdir -p ${DESTDIR}${PREFIX}/sbin/
 	mv ${DESTDIR}${PREFIX}/bin/pcs ${DESTDIR}${PREFIX}/sbin/pcs
-	install -D -m644 pcs/bash_completion.sh ${BASH_COMPLETION_DIR}/pcs
+	install -D -m644 pcs/bash_completion.sh ${DESTDIR}${BASH_COMPLETION_DIR}/pcs
 	install -m644 -D pcs/pcs.8 ${DESTDIR}/${MANDIR}/man8/pcs.8
 ifeq ($(IS_DEBIAN),true)
   ifeq ($(install_settings),true)
@@ -100,7 +101,7 @@
 
 install_pcsd:
 ifeq ($(BUILD_GEMS),true)
-	make -C pcsd build_gems
+	DESTDIR= make -C pcsd build_gems
 endif
 	mkdir -p ${DESTDIR}/var/log/pcsd
 ifeq ($(IS_DEBIAN),true)
@@ -117,10 +118,10 @@
 	        rm -f $$tmp_settings_pcsd
   endif
   ifeq ($(IS_SYSTEMCTL),true)
-	install -d ${DESTDIR}/${systemddir}/system/
-	install -m 644 pcsd/pcsd.service.debian ${DESTDIR}/${systemddir}/system/pcsd.service
+	install -d ${DESTDIR}${systemddir}/system/
+	install -m 644 pcsd/pcsd.service.debian ${DESTDIR}${systemddir}/system/pcsd.service
   else
-	install -m 755 -D pcsd/pcsd.debian ${DESTDIR}/${initdir}/pcsd
+	install -m 755 -D pcsd/pcsd.debian ${DESTDIR}${initdir}/pcsd
   endif
 else
 	mkdir -p ${DESTDIR}${PREFIX}/lib/
@@ -129,13 +130,13 @@
 	install -d ${DESTDIR}/etc/pam.d
 	install  pcsd/pcsd.pam ${DESTDIR}/etc/pam.d/pcsd
   ifeq ($(IS_SYSTEMCTL),true)
-	install -d ${DESTDIR}/${systemddir}/system/
-	install -m 644 pcsd/pcsd.service ${DESTDIR}/${systemddir}/system/
+	install -d ${DESTDIR}${systemddir}/system/
+	install -m 644 pcsd/pcsd.service ${DESTDIR}${systemddir}/system/
 # ${DESTDIR}${PREFIX}/lib/pcsd/pcsd holds the selinux context
 	install -m 755 pcsd/pcsd.service-runner ${DESTDIR}${PREFIX}/lib/pcsd/pcsd
 	rm ${DESTDIR}${PREFIX}/lib/pcsd/pcsd.service-runner
   else
-	install -m 755 -D pcsd/pcsd ${DESTDIR}/${initdir}/pcsd
+	install -m 755 -D pcsd/pcsd ${DESTDIR}${initdir}/pcsd
   endif
 endif
 	install -m 700 -d ${DESTDIR}/var/lib/pcsd
@@ -150,9 +151,9 @@
 	rm -rf ${DESTDIR}${PREFIX}/lib/pcsd
 endif
 ifeq ($(IS_SYSTEMCTL),true)
-	rm -f ${DESTDIR}/${systemddir}/system/pcsd.service
+	rm -f ${DESTDIR}${systemddir}/system/pcsd.service
 else
-	rm -f ${DESTDIR}/${initdir}/pcsd
+	rm -f ${DESTDIR}${initdir}/pcsd
 endif
 	rm -f ${DESTDIR}/etc/pam.d/pcsd
 	rm -rf ${DESTDIR}/var/lib/pcsd
